### ISSUE TITLE
[Task 2.1] Review

### ISSUE THREAD

**Issue by alex-ks** [edubinskaya18214/OOP#3]
- У `StackElem` (зачем такое сокращение?) аж два метода для задания следующего элемента (зачем?) и ни одного - для предыдущего. Пожалуйста, сделай консистентный интерфейс
- В `push(T n)` n - такое себе название для добавляемого элемента. Ограничение, что в стек нельзя добавить `null`, выглядит странным (зря ты не хочешь использовать исключения), и, кроме того, комментарий к методу недостаточно чётко определяет это поведение: "размер не увеличится" не означает "элемент не будет добавлен"
- При удалении последнего элемента в стеке у тебя никак не меняется `head`, что приводит к забавным спецэффектам в итераторе
  - Отличный повод сделать на это тест!
- `next` у итератора выбрасывает исключение, отличающееся от определённого в документации
  - И страдает от той же проблемы, что и `hasNext` - сразу видно, что нет тестов на пустой стек
- `FindFirstElem` нигде не используется
- `public class tests` - это какое-то особое издевательство над Code Style
- Писать `System.out.println("int test is successful");` в конце каждого теста не нужно - тестовый фреймворк и так делает это за тебя
- В чём тайный смысл писать `if (!s.pop().equals(a.remove(a.size() - 1))) Assert.fail();` вместо `Assert.asserEquals`? Так ты не увидишь сами значения, если тест поломается
- Грамматические ошибки в тестовых данных =(

**Comment by edubinskaya18214** [comment]
1) Удалила один из методов добавления нового элемента(CreateNextELem), добавила способ задания предыдущего(addPreviousElem) и переименовала класс на StackElement
  2) Добавила исключение на вставку null, переписала комментарии. Переписала тесты, чтобы они проверяли выброс исключения
  3) Добавила проверку - присваиваю head = null при удалении последнего элемента, написала на это тест( последний тест в классе).
  4) изменила исключение в документации, и вправду странно-глупый косяк.
  5) удалила функцию, в прошлый раз об этом забыла, вместо неё используем head.
  6) переименовала, постараюсь так не издеваться.
  7) удалила сообщения об успешности тестов.
  8) тайного смысла нет, почему то тогда это казалось логичным, заменила на Assert.assertEquals.
  9) я постаралась исправить что увидела.

**Comment by edubinskaya18214** [comment]
> * У `StackElem` (зачем такое сокращение?) аж два метода для задания следующего элемента (зачем?) и ни одного - для предыдущего. Пожалуйста, сделай консистентный интерфейс
> * В `push(T n)` n - такое себе название для добавляемого элемента. Ограничение, что в стек нельзя добавить `null`, выглядит странным (зря ты не хочешь использовать исключения), и, кроме того, комментарий к методу недостаточно чётко определяет это поведение: "размер не увеличится" не означает "элемент не будет добавлен"
> * При удалении последнего элемента в стеке у тебя никак не меняется `head`, что приводит к забавным спецэффектам в итераторе
>   
>   * Отличный повод сделать на это тест!
> * `next` у итератора выбрасывает исключение, отличающееся от определённого в документации
>   
>   * И страдает от той же проблемы, что и `hasNext` - сразу видно, что нет тестов на пустой стек
> * `FindFirstElem` нигде не используется
> * `public class tests` - это какое-то особое издевательство над Code Style
> * Писать `System.out.println("int test is successful");` в конце каждого теста не нужно - тестовый фреймворк и так делает это за тебя
> * В чём тайный смысл писать `if (!s.pop().equals(a.remove(a.size() - 1))) Assert.fail();` вместо `Assert.asserEquals`? Так ты не увидишь сами значения, если тест поломается
> * Грамматические ошибки в тестовых данных =(

Удалила один из методов добавления нового элемента(CreateNextELem), добавила способ задания предыдущего(addPreviousElem) и переименовала класс на StackElement
Добавила исключение на вставку null, переписала комментарии. Переписала тесты, чтобы они проверяли выброс исключения
Добавила проверку - присваиваю head = null при удалении последнего элемента, написала на это тест( последний тест в классе).
изменила исключение в документации, и вправду странно-глупый косяк.
удалила функцию, в прошлый раз об этом забыла, вместо неё используем head.
переименовала, постараюсь так не издеваться.
удалила сообщения об успешности тестов.
тайного смысла нет, почему то тогда это казалось логичным, заменила на Assert.assertEquals.
я постаралась исправить что увидела.
