### ISSUE TITLE
[Task 4.1] Удаление решений в ветке

### ISSUE THREAD

**Issue by alex-ks** [edubinskaya18214/OOP#4]
Екатерина, скажи, что сподвигло тебя удалить в ветке `4.1` все предыдущие изменения? Для справки: т.к. ты закоммитила *удаление* всех файлов в ветке `4.1`, то при влитии этой ветки в `master` из него удалятся все файлы так же, как они были удалены из `4.1`

**Comment by alex-ks** [comment]
А ещё директория с решением задачи называется не правилам.

**Comment by edubinskaya18214** [comment]
Я не знаю, мне показалось это логичным, видимо не очень, ну я могу восстановить старую ветку и переименовать директорию, если  это очень важно.

**Comment by edubinskaya18214** [comment]
Я не знаю, мне показалось это логичным, видимо не очень, ну по крайней мере вы говорили что то вроде того, что все задания должны быть на разных ветках.. Я могу восстановить старую ветку и переименовать директорию, если это очень важно.

> Екатерина, скажи, что сподвигло тебя удалить в ветке `4.1` все предыдущие изменения? Для справки: т.к. ты закоммитила _удаление_ всех файлов в ветке `4.1`, то при влитии этой ветки в `master` из него удалятся все файлы так же, как они были удалены из `4.1`

**Comment by alex-ks** [comment]
> все задания должны быть на разных ветках

Имеется в виду, что код решения должен появляться в отдельной ветке (и что его не должно быть в мастере). Но при этом всё остальное в ветке меняться не должно - иначе все эти изменения попадут в мастер вместе с решением задачи при влитии ПР.
