### ISSUE TITLE
[Task 4.1] Review

### ISSUE THREAD

**Issue by alex-ks** [edubinskaya18214/OOP#5]
- Реализации операций имеет смысл вынести в отдельный пакет
- Для фабрики имеет стоит сделать собственный интерфейс - так проще будет делать поддержку нескольких фабрик из подключаемых `.jar`
- Для чего нужно поле `useAns` в `Calculator`? Кажется, что оно всегда `false`
- `Answers` - имя поля не по code style
- `List<String> string` - бесконечно говорящее имя=)
- Очень необычная реализация функции `isDelimiter`. Чем не подошла проверка `c != ' '`?
- Вообще про реализацию `parseAndSave`: Поскольку входные строки короткие, лучше посмотри на [String.split](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-) - так будет проще
- Не самый лучший подход к реализации функции `isOperator`. Если тебе нужно будет добавить новую операцию, недостаточно будет поправить фабрику - нужно будет ещё править и эту функцию. Т.к. у нас нет переменных, правильнее будет определить, что всё, что не является числом, является операцией; либо можно сделать у фабрики метод "isOperationSupported", и реализовать `isOperator` через него
- В `counting` лучше выбрасывать исключения с каким-то пояснительным текстом, а ещё лучше и с номером токена от начала строки, на котором произошла ошибка
- Про имя `counting`: методы принято называть инфинитивом, а не герундием, если это не проверка статуса (`isDoingSomething`).
- Реализация `counting` выглядит как-то неочевидно. Что за pos и почему это `string.size() - 2`? А ещё эта реализация плохо дружит с функциями с 0 аргументов (a la константы, например, `e`). Вообще, стековый калькулятор обычно делают либо рекурсивно (достаём операцию, достаём аргументы, если среди них встретили операцию - запускаем рекурсию), либо на двух стеках - один для операций, другой - для значений
- Сейчас у тебя довольно большие тесты, которые, по факту, являются кучей отдельных тестов в одном. Разбей их на отдельные сценарии и дай соответствующие имена

**Comment by edubinskaya18214** [comment]
> * Реализации операций имеет смысл вынести в отдельный пакет
Вынесла.

> * Для фабрики имеет стоит сделать собственный интерфейс - так проще будет делать поддержку нескольких фабрик из подключаемых `.jar`

> * Для чего нужно поле `useAns` в `Calculator`? Кажется, что оно всегда `false`
Я думала, что будет наверное логично если можно будет ещё и отключать функцию использования ответов,а не только сохранения, но потом поняла что проверка занимает довольно таки мало времени, и решила не создавать функцию для изменения флажка, забыв удалить сам флажок.

> * `Answers` - имя поля не по code style
теперь это `savedExpressions`

> * Очень необычная реализация функции `isDelimiter`. Чем не подошла проверка `c != ' '`?
Заменила на `c != ' '`.

> * Вообще про реализацию `parseAndSave`: Поскольку входные строки короткие, лучше посмотри на [String.split](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-) - так будет проще
Вышло и в правду неплохо, всю функцию заменила 1 строка.(32)

> * Не самый лучший подход к реализации функции `isOperator`. Если тебе нужно будет добавить новую операцию, недостаточно будет поправить фабрику - нужно будет ещё править и эту функцию. Т.к. у нас нет переменных, правильнее будет определить, что всё, что не является числом, является операцией; либо можно сделать у фабрики метод "isOperationSupported", и реализовать `isOperator` через него
Перенесла этот метод в фабрику.

> * В `counting` лучше выбрасывать исключения с каким-то пояснительным текстом, а ещё лучше и с номером токена от начала строки, на котором произошла ошибка
Теперь исключения выводят ошибку и токен на которм была поломка.

> * Про имя `counting`: методы принято называть инфинитивом, а не герундием, если это не проверка статуса (`isDoingSomething`).
Переименовала в `calculateExpression()`

> * Реализация `counting` выглядит как-то неочевидно. Что за pos и почему это `string.size() - 2`? А ещё эта реализация плохо дружит с функциями с 0 аргументов (a la константы, например, `e`). Вообще, стековый калькулятор обычно делают либо рекурсивно (достаём операцию, достаём аргументы, если среди них встретили операцию - запускаем рекурсию), либо на двух стеках - один для операций, другой - для значений
Я не подумала про функции от нуля аргументов, исправила. `pos` тоже переименовала `tokenNumber`.

> * Сейчас у тебя довольно большие тесты, которые, по факту, являются кучей отдельных тестов в одном. Разбей их на отдельные сценарии и дай соответствующие имена
